#!/bin/sh
lib="$(git rev-parse --show-toplevel)"
pkg="$lib/blink"

uid="$(id -u)"
gid="$(id -g)"

(set -x
  docker run \
    --rm \
    --interactive \
    --tty \
    --user "$uid:$gid" \
    --device /dev/ttyUSB0 \
    --volume "$pkg:/wrk" \
    --workdir /wrk \
    docker.io/espressif/idf:v4.2 \
    idf.py \
    -p /dev/ttyUSB0 \
    flash)
